### ISSUE TITLE
Doesn't make requests, returns undefined.

### ISSUE THREAD

**Issue by leqwasd** [Catbuttes/axios-ntlm#2]
Just started on a project.
Project consists of express, webpack, typescript.

I am trying this out, as from the documentation.
```
        const ntlmClient = NtlmClient({
            username: "username",
            password: "password",
            domain: "domain"
        });
        await ntlmClient
            .get("https://fullUrl.com?f=pjson")
            .then((r) => {
                logger.info("In the response");
                logger.info(r);
            });
```

in the response, r is always undefined. I haven't set up my project to be able to attach to it yet. But looking at fiddler, it is not making any requests at all. It also does not respond to invalid credentials. The response is the same - undefined.

I cloned your repositry, trying to debug the thing.

```typescript
client.interceptors.response.use((response) => {
        return response;
    }, (err:AxiosError) => {
        let error: AxiosResponse|undefined = err.response;

        if (error && error.status === 401
            && error.headers['www-authenticate']
            && error.headers['www-authenticate'].includes('NTLM')
            // This length check is a hack because SharePoint is awkward and will 
            // include the Negotiate option when responding with the T2 message
            // There is nore we could do to ensure we are processing correctly,
            // but this is the easiest option for now
            && error.headers['www-authenticate'].length < 50
            && !err.config.headers['X-retry']) {

            let t1Msg = ntlm.createType1Message(credentials.workstation!, credentials.domain);

            error.config.headers["Authorization"] = t1Msg;
            let resp = client(error.config);

            return resp;
        }
        else if (error && error.status === 401
            && error.headers['www-authenticate']
            && error.headers['www-authenticate'].length > 50
            && error.headers['www-authenticate'].includes('NTLM')) {
            
            let t2Msg = ntlm.decodeType2Message((error.headers['www-authenticate'].match(/^NTLM\s+(.+?)(,|\s+|$)/) || [])[1]);
            
            let t3Msg = ntlm.createType3Message(t2Msg, credentials.username, credentials.password, credentials.workstation!, credentials.domain);

            error.config.headers["Authorization"] = t3Msg;

            let resp = client(error.config);

            return resp;
        }
        else {
            return error;
        }
    });
```

I would say, there is a problem here. It swallows errors. err was something like this: 
```json
{
  "CODE": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
  "message": "unable to get local issuer certificate",
  "stack": "Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at TLSSocket._finishInit (_tls_wrap.js:666:8)"
}
```
err had no response, so error = undefined.
You are returning undefined error in the last else. Shouldn't it be err?

For the time being I fixed this with:
```typescript
    const httpsAgent = new https.Agent({
        rejectUnauthorized: false,
        keepAlive: true
    });
    const config: AxiosRequestConfig = {
        httpsAgent
    }
```

At first, it went into infinite lopps, because I did not set `keepAlive: true`, 
And these lines did not execute, because I had passed my own httpsAgent.
```
    if(!config.httpAgent) {
        config.httpAgent = new http.Agent({keepAlive: true}); 
    }

    if(!config.httpsAgent) {
        config.httpsAgent = new https.Agent({keepAlive: true}); 
    }
```

**Comment by Catbuttes** [comment]
I'm afraid I am going to need a few more details on your setup - do you have a minimum complete setup that displays this behaviour? I have not been able to replicate it using the following code (which I believe respresents your code well) :

```js
import { NtlmClient, NtlmCredentials } from 'axios-ntlm';

(async () => {

    let credentials: NtlmCredentials = {
        username: 'user',
        password: "pass",
        domain: 'domain'
    }

    let client = NtlmClient(credentials)

    try {

        await client.get('my.ntlm.url')
        .then((r) => {
            console.log("In the response");
            console.log(r);
        });
    }
    catch (err) {
        console.log(err)
        console.log("Failed")
    }

})()
```

**Comment by Catbuttes** [comment]
Just another note - this library relies on the Node JS standard library. It will not work in the browser (and I don't believe should be required as the browser will handle the authentication for you). I have _not_ tested it with any other runtimes such as Deno.

**Comment by leqwasd** [comment]
The reason, you are not able to reproduce my example, is not because of the code, but because of the network, and servers you are connecting to. With yours, I thing everything is all right, so you can't reproduce.

A reprocudable example:
Try to post anything to some made up URL. I would expect this code to throw, but it doesn't.
```typescript
// axios-ntml client
client({
    method: "GET",
    url: "https://asdasd"
})
    .then((resp) => {
        console.log(resp); // undefined
    })
    .catch((ex) => {
        console.error(ex); // not hit
    });
// default axios
axios({
    method: "GET",
    url: "https://asdasd"
})
    .then((resp) => {
        console.log(resp); // not hit
    })
    .catch((ex) => {
        console.error(ex); // error
    });
```

**Comment by Catbuttes** [comment]
I see what you mean. I have just release v1.1.6 which should fix this
